services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: i2a2-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/reports:/app/reports
    ports:
      - "8080:8080"
    restart: unless-stopped
