version: '3.8'

services:
  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development

  ollama:
    image: ollama/mistral
    ports:
      - "8080:8080"
    volumes:
      - ollama_data:/data

volumes:
  ollama_data: